### ISSUE TITLE
Add Scythes from SW 1.12.2-1.6.0

### ISSUE THREAD

**Issue by brisingraerowing** [Invadermonky/SpartanNetherite#2]
Spartan Weaponry 1.12.2-1.6.0 backported Scythes from newer versions. Could that be added to this mod?

**Comment by Invadermonky** [comment]
Yeah I can add these pretty easily. It will require a major version update as it will be incompatible with older versions of Spartan Weaponry.

~~I will likely also rewrite some of the code to remove the dependency with Future MC just in case someone wants to use a different mod that adds Netherite.~~ Removed this as I have another idea for handling this.

**Comment by Invadermonky** [comment]
Completed as of [Version 1.12.2-1.1.0](https://www.curseforge.com/minecraft/mc-mods/spartan-netherite/files/5663599)
